QuEraComputing/bloqade-circuit

src/bloqade/squin/groups.py
Importing this pass from `qasm2` makes it so that the regular installation without the extras breaks because `lark` is not a part of the default list of dependencies. Also this pass is needed only for the `qasm2.core` dialect to add support for indexing of QRegisters which are not a part of squin.
=> Removing unneeded pass

src/bloqade/squin/analysis/nsites/analysis.py
As a consequence of the revisions requested from #11 some of my original comments don't make sense with the new naming scheme so I opted to either remove/revise them so future maintenance doesn't get too confusing due to them
=> revise some outdated squin analysis comments

src/bloqade/qasm2/rewrite/native_gates.py, test/qasm2/test_native.py
Since #163 might be a while (depending on a change in kirin and whether we are fixing more pyright issues), I figured it might make sense to split out the bug fix. I cherry-picked the commit from the other PR.
The test isn't great, but it fails on the current main branch and works here, so better than nothing.
=> Fix native cu3 rewrite if clause

src/bloqade/pyqrack/noise/native.py, test/pyqrack/runtime/noise/native/test_pauli.py, test/pyqrack/runtime/test_dyn_memory.py
should close #169 caused by the simulator getting to a weird state where the probability of measuring |0> becomes probability 0.0 causing the interpreter to crash when an atom is lost during noise simulations. We keep track of the atom state
=> Removing `form_m` from pyqrack interpreter. 

src/bloqade/analysis/address/impls.py, src/bloqade/noise/native/model.py, src/bloqade/qasm2/parse/lowering.py, src/bloqade/qasm2/passes/fold.py, src/bloqade/qasm2/rewrite/heuristic_noise.py, src/bloqade/qasm2/rewrite/native_gates.py, src/bloqade/qasm2/rewrite/register.py, src/bloqade/qasm2/rewrite/uop_to_parallel.py, src/bloqade/qbraid/schema.py, src/bloqade/squin/analysis/nsites/analysis.py, src/bloqade/visual/animation/base.py
Got it down to 14 errors (starting out with 69). Not sure if all changes make sense.
The errors that are left are mostly ones such as this:
```python
kirin-workspace/bloqade-circuit/src/bloqade/stim/emit/stim.py:35:9 - error: Method "emit_block" overrides class "EmitABC" in an incompatible manner
Return type mismatch: base method returns type "str", override returns type "str | None"
Type "str | None" is not assignable to type "str"
"None" is not assignable to "str" (reportIncompatibleMethodOverride)
```
I'm not sure what the best way to deal with those method overrides is.
Also, there's still a bunch of errors in `visual/animation`, which I could fix, but it would require some type assertions here and there (i.e. actually raising an error if the type expectation is not met) and I didn't …
=> Fix some pyright issues

src/bloqade/pyqrack/qasm2/core.py, src/bloqade/qasm2/_wrappers.py, src/bloqade/qasm2/dialects/core/stmts.py, test/pyqrack/test_target.py
=> Support measuring registers in pyqrack

src/bloqade/qasm2/parse/lowering.py, test/qasm2/test_lowering.py
closes #10 and #183, needs a test.
=> Missing push statement to frame

src/bloqade/squin/op/stmts.py, src/bloqade/squin/qubit.py
This PR is addressing the new squin statements. However, after discussion with @kaihsin and @Roger-luo we have slightly modified the semantics to make things a bit cleaner:
1. `Boradcast` is now an appliy-like statement, see #206 
2.  `PualiString` is now `CliffordString` to enable better rewrites to STIM.
=> New Squin statements. 

src/bloqade/noise/native/stmts.py, test/pyqrack/runtime/noise/native/test_loss.py, test/pyqrack/runtime/noise/native/test_pauli.py
Closes #164 
**Note**: still need to test it, blocked by the issue I have (similar to the one in #183 )
=> Implement probability checks for native noise statements

pyproject.toml
I am also making pyqrack-cpu implementation a default dependency since it has no other dependencies it is pretty light
=> Add pyqrack extas with platform dependent constraints. 

src/bloqade/qasm2/passes/noise.py, src/bloqade/qasm2/rewrite/heuristic_noise.py, src/bloqade/qasm2/rewrite/uop_to_parallel.py
fixes:
* ParallelToUop I just added a `setdefault` so that it would register the dictionary value and then overwrite it later
* For RewriteNoiseModel: I split up the rewrites to be correct when having the new traversal order.
=> Fixing bugs related to kirin 0.17.3 version. 

src/bloqade/squin/groups.py, src/bloqade/squin/qubit.py, src/bloqade/squin/rewrite/measure_desugar.py, test/squin/test_measure_sugar.py
=> Measure Refactor. 

src/bloqade/pyqrack/qasm2/uop.py, test/pyqrack/runtime/test_qrack.py
Note if you look at the definition of the Pauli enum https://github.com/unitaryfoundation/pyqrack/blob/819c58aed5a5695ee0a21f6274575b55deecb791/pyqrack/pauli.py#L17 y -> 3 and z -> 2 which is pretty weird lol. 
cc: @david-pl
=> Fixing bug with wrong enum value

test/qasm2/passes/test_heuristic_noise.py
In the new kirin patch the traversal order of the statements during a `Walk` rewrite pass has changed again so I have fixed the test to match the traversal order of `Walk`.
=> Fixing test to match statement traversal order

src/bloqade/squin/wire.py, test/squin/test_constprop.py
This adds `broadcast` from the qubit dialect into the `wire` dialect as well for squin. I added unit tests specifically for constprop as well and took @weinbe58 's feedback to add things into the constprop impl.
I'll be very honest, I just carried over my work from #217 because I think I did some improper merge and it broke something somewhere else 😅 and the CI failing but my local run working was annoying me too much.
=> Add broadcast to wire

src/bloqade/pyqrack/base.py, test/pyqrack/test_target.py
I'm gonna open an issue on PyQrack repo about this it would be good to know what are good flags to pass into the `QrackSimulator` object. Currently, some configurations of options will cause a runtime error when executing the simulation instead of a value error when constructing the object. I'll add validation on the arguments passed into the `QrackSimulator` object as we slowly figure out the bad behavior.
=> Fix default arguments for PyQrack. 

src/bloqade/squin/op/stmts.py
Per yesterday's meeting Scientific Software meeting agreement, the Clifford string operator should be restricted to just Pauli's. 
@weinbe58 @Roger-luo I know there were several methods mentioned to translating the string into an actual `OpType` that can be used in other statements, ranging from lowering, canonicalization rewrite, etc. What is the _exact_ approach that should be taken for this? I'd like to open an issue to keep track of the infrastructure required for this.
cc: @cduck @kaihsin
=> Change Clifford String to Pauli String

src/bloqade/squin/__init__.py, src/bloqade/squin/noise/__init__.py, src/bloqade/squin/noise/_dialect.py, src/bloqade/squin/noise/stmts.py
Some initial friction points/anticipated changes I can immediately see in translating this to stim
- The original `PauliChannel` definition from @kaihsin can take a variable number of float arguments, but in the stim dialect there are explicit fields for each probability of a 1Q/2Q pauli operator being applied. My feeling is that this should be reflected on the squin side as just something like `1QPauliChannel` and `2QPauliChannel` with explicit fields. I don't think we'd lose any generality here along with the added benefit that it would be much harder for a user to misinput information (the default definition assumes you plug in either 3 or 15 values via varargs but it seems to easy to make a mistake here)
- ~~If we DO want varargs I'm not quite sure how to nicely feed this to the kirin …
=> Adding noise statements to squin

src/bloqade/squin/groups.py, src/bloqade/squin/op/__init__.py, src/bloqade/squin/op/complex.py, src/bloqade/squin/op/number.py, src/bloqade/squin/op/rewrite.py, src/bloqade/squin/op/stmts.py, src/bloqade/squin/op/types.py, test/squin/test_mult_rewrite.py
Seemed sufficiently different from #207, so I created a new branch for it.
@Roger-luo two things:
* I'm not sure whether this should be a `Fixpoint`.
* Should this also be part of the `wire` kernel?
=> Rewrite py.Mult to squin.Mult in squin kernel

src/bloqade/qasm2/passes/lift_qubits.py, src/bloqade/qasm2/passes/noise.py, src/bloqade/qasm2/rewrite/heuristic_noise.py, src/bloqade/qasm2/rewrite/insert_qubits.py
in issue #226 The problem is because how the qubit -> global index. In this PR I add an explicit pass that lifts all qubit references to the top of the entry block.
=> Fixing NoisePass with LiftQubits Pass.

src/bloqade/squin/wire.py, test/squin/test_constprop.py
@Roger-luo has fixed Kirin's constprop to [handle multiple result values](https://github.com/QuEraComputing/kirin/pull/393) (:  the custom constprop for certain wire statements is no longer needed
=> remove custom constprop for wire

src/bloqade/qasm2/__init__.py, src/bloqade/qasm2/_qasm_loading.py
address #238 one question tho, was there a particular reason why the `loads` and `loadfile` was living inside the lowering target? @weinbe58 I think if not would be nice to move them out. This is not an object we expect users to use directly cuz it would be too confusing without knowing about lowering process.
=> simplify loads

src/bloqade/qasm2/passes/noise.py, src/bloqade/qasm2/rewrite/heuristic_noise.py, test/qasm2/passes/test_heuristic_noise.py
closes https://github.com/QuEraComputing/bloqade-circuit/issues/232 The reason the previous fix didn't work is because of how the values of `frame.entries` are iterated over. The old code assumed that the traversal was in the order of the statements in the IR but this is not neccesarily True. In this fix I traverse the IR and extract the global qubit IDs to pass into the NoiseRewrite. This should definitely fix the problems going foward.
=> Fixing extraction of global qubit ids

src/bloqade/qasm2/_qasm_loading.py, src/bloqade/qasm2/parse/lowering.py, test/qasm2/test_lowering.py
follow up #240 I removed the `returns` option cuz it seems no one is using it. We can add something back if there is an actual user asking for it.
I'm not sure why it was copy pasting `QASM2.run` method in the old `loads` implementation, maybe there was some issue with the lowering so this was a workaround? @weinbe58
=> cleanup loads/loadfile in lowering

src/bloqade/qasm2/parse/__init__.py
this PR adds an option `no_color` so one does not need to create a rich Console manually.
=> allow printing QASM2 without color

src/bloqade/squin/wire.py
On the heels of @weinbe58 's request and input from @cduck this PR just proposes moving away from the old NonDestructiveMeasure name (which caused some confusion over what exactly was being "destroyed") and opting for something a bit clearer. 
I remember there weren't any objections to something along the lines of "Loss Resolving Readout" so I propose Loss Resolving "Measure" but perhaps there might be some objections or other ideas. I don't know if it would be helpful either to "flip" the intent behind the measures (potential via renaming the default Measure) considering @cduck has mentioned Loss Resolution is the more common, normal mode of operation as opposed to the destructive/"lossy" form.
=> RFC: Move away from NonDestructiveMeasure in squin.wire dialect name

src/bloqade/squin/rewrite/desugar.py, test/squin/rewrite/test_desugar.py
Currently the `ApplyDesugarRule` will make certain assumptions about the type of the input. In this PR I check for all potential types and input shapes and if none of them match the rewrite doesn't apply the desugar.
=> Fix Desugar pass to "give up" when type inference fails. 

src/bloqade/analysis/address/impls.py, test/analysis/address/test_analysis.py
This allows slicing to work with the address analysis pass.
@liupengy19 ran into this problem with some of his work and @david-pl helped me confirm the issue was not specific to my setup (: 
Note: the way the tests are written for the address analysis are definitely a bit outdated, I believe once #370 goes through I updated the tests there so it will just be a matter of merging in the new updated stuff
=> Allow slicing to work with address analysis

src/bloqade/squin/op/stmts.py
I noticed a warning about `\p` being an invalid escape sequence when running unit tests locally and found it came from the way the docstrings in the squin ops were being defined. 
This should get rid of the warning as well as fix the rendering on the docs page, which has some incorrect rendering:
=> Fix warning about invalid escape sequence

src/bloqade/squin/noise/rewrite.py, test/pyqrack/squin/test_noise.py
Another thing that came out of #436.
=> Implement squin noise rewrite for depolarize2

src/bloqade/squin/op/_wrapper.py, src/bloqade/squin/stdlib/gate.py
Closes #329 .
@Roger-luo I'm wondering whether this is sufficient. There was no documentation before so maybe that was just the issue. I don't know, I just really dislike the idea of having e.g. `rot_rad`. It also doesn't make complete sense since there is another argument there that's not an angle. I will change to that if you think just having nice docstrings is insufficient.
=> Clearly document the units of angles in wrappers

src/bloqade/cirq_utils/emit/base.py, test/cirq_utils/test_clifford_to_cirq.py
Closes #527 .
@weinbe58 I originally tried to simply keep a function from being cached if it allocates new qubits. In principle, I had all the information there via the `sub_frame.qubit_index`, which, if incremented, would reflect that there have been qubits allocated.
However, when I had that, there was still _something_ off with the caching: it would sometimes produce a circuit that applied two Hadamard gates to the first qubit and none to the third one. The odd part was that this only occurred sometimes, other times the circuit looked fine. I'm not entirely sure what the cause was here, but probably something with caching the stdlib calls to `squin.h(q[0])`.
Also, there's probably a bug if you supply a custom list of `cirq` qubits, since that's not passed into the `sub_frame` as far as …
=> Inline function invokes when emitting a cirq circuit
